export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //bottom
  HOME_SCREEN: 'HOME_SCREEN',

  //auth
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  FORGET_PASSWORD_SCREEN: 'FORGET_PASSWORD_SCREEN',
};
