export default {
  // Root Main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  // Bottom Tab
  HOME_SCREEN: 'HOME_SCREEN',

  // Common Screen

  CHART_SCREEN: 'CHART_SCREEN',
};
