export default {
  // Root Main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  // Bottom Tab
  HOME_SCREEN: 'HOME_SCREEN',

  // Common Screen

  WIFI_SCREEN: 'WIFI_SCREEN',
  CHANGE_TITLE_SCREEN: 'CHANGE_TITLE_SCREEN',
  CONFIG_MODE_SCREEN: 'CONFIG_MODE_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  SCAN_WIFI_SCREEN: 'SCAN_WIFI_SCREEN',
  CHANGE_KEY_SCREEN: 'CHANGE_KEY_SCREEN',
};
